Forms
BonkeGcobo/blog-app pull request #6
Opened 2022-06-22 15:21 UTC by BonkeGcobo

## Description

- [x] current_user to be able to create a post
- [x] current_user is able to comment on a post
- [x]  Users can like a post

Happy Reviewing

2022-06-22 17:08 UTC, Gambit142 requested changes
Hi @BonkeGcobo 👋, 

Good job so far!

## Highlights
- Has `new` and `create` actions in `Post` Controller ✔️ 
- Has `new` and `create` actions in `Comment` Controller ✔️ 
- Has view files for `Post` and `Comment` models ✔️
- Has routes that leads to `Post#new` and `Post#create` ✔️ 
- Has routes that leads to `Comment#new` and `Comment#create` ✔️ 
-  Has `new` and `create` actions in `Like` Controller ✔️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-22 17:08 UTC, Gambit142 commented on app/controllers/comments_controller.rb
> +    comment.user = user
- [x] When creating a `Comment`, it would be nice to make use of strong parameters. Strong parameters ensure that only attributes permitted are accepted when creating a model. It also prevents people who have malicious intentions from adding and configuring what type of data is sent to the database. To use strong parameters kindly read this [article](https://api.rubyonrails.org/classes/ActionController/StrongParameters.html). 

- Remember to make the params method private. 👍

2022-06-22 17:08 UTC, Gambit142 commented on app/controllers/posts_controller.rb
> +    post.user = user
- [x] When creating a `Post`, it would be nice to make use of strong parameters. Strong parameters ensure that only attributes permitted are accepted when creating a model. It also prevents people who have malicious intentions from adding and configuring what type of data is sent to the database. To use strong parameters kindly read this [article](https://api.rubyonrails.org/classes/ActionController/StrongParameters.html). 

- Remember to make the params method private. 👍

2022-06-22 17:08 UTC, Gambit142 commented on app/views/posts/new.html.erb
> +<%= stylesheet_link_tag "form" %>
- [x] When I route to the Post#new page, I get an error because of this line of code:

![image](https://user-images.githubusercontent.com/77106962/175094497-96282cef-611a-4968-a448-e1df5ca8dec6.png)

Kindly work on the error. I would advise you to not use to use the line of code and style using your **_CSS/SCSS_** files. 👍

2022-06-22 17:08 UTC, Gambit142 commented on app/views/posts/_post_info.html.erb
> +      <%= link_to 'Likes:', new_user_post_like_path(post_id: post.id) %> <%=likesCounter%>
- [x] [Optional] For a better user experience, it would be nice to use buttons or style the links to look like they are buttons. You can then have a span element that displays the number of comments and the number of likes differently. This way, a user will be to comment or like a post easily. Remember that a user will not see your code to know that those are links to commenting on a post or liking a post.👍

2022-06-23 09:00 UTC, BonkeGcobo commented on app/views/posts/_post_info.html.erb
> +      <%= link_to 'Likes:', new_user_post_like_path(post_id: post.id) %> <%=likesCounter%>
I will add this link end of this week when, I add my own styles on the project, for now I want to get the core functionality up and running

2022-06-23 09:24 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @BonkeGcobo,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [x] When I start up your app I get this error in the application controller (see image). Kindly fix it. I think you meant:

  ```
  ...
  user = User.find_by(id: id)
  ...
  ```
  ![err-gombo](https://user-images.githubusercontent.com/36542986/175265489-d9e5fe4c-632d-4e41-ad87-c371b124293b.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 10:39 UTC, BonkeGcobo commented
@TedLivist, thanks for your review

When I run rubocop, the statement `User.find_by(id :id)` IT changes to `User.find_by(id:)`.


I don't think this is an issue because when the hash_key and parameter containing hash_value have the same name I think this could be done. It is also running on my PC

This is the rubocop error I get below
![Code-Review](https://user-images.githubusercontent.com/38408119/175280249-c19329d6-e334-46a6-9d2b-1b02b6cce26c.JPG)

2022-06-23 10:58 UTC, TedLivist commented
@BonkeGcobo Alright then. No problem. Leave it as it was earlier since this is not an issue.

2022-06-23 11:22 UTC, FrederickMih approved these changes
# Status: Approved :tada: :tada: 

Hi @BonkeGcobo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 13:21 UTC, merged